// Generated by Wrangler on Fri Nov 17 2023 11:19:38 GMT+0800 (台北標準時間)
interface Env {
	// If you set another name in wrangler.toml as the value for 'binding',
    // replace "DB" with the variable name you defined.
	DB: D1Database;
}
